<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Tori-kaupat</name>
   <tag></tag>
   <elementGuidId>6c252e3c-635c-4494-bd1d-a2f365dd332c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='li']/div/div/div/ul/li[4]/a/p</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Tori-kaupat' or . = 'Tori-kaupat')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav_text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tori-kaupat</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;li&quot;)/div[@class=&quot;header clear&quot;]/div[@class=&quot;nav_container&quot;]/div[@class=&quot;navigation navigation_mc nohistory navigation_left&quot;]/ul[@class=&quot;navigation_items&quot;]/li[@class=&quot;navigation_item_container&quot;]/a[@class=&quot;navigation_item&quot;]/p[@class=&quot;nav_text&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//body[@id='li']/div/div/div/ul/li[4]/a/p</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//li[4]/a/p</value>
   </webElementXpaths>
</WebElementEntity>
